exports.articleController = require('./articleController')
exports.authController = require('./authController')
exports.chatController = require('./chatController')
exports.consultantController = require('./consultantController')
exports.partnershipController = require('./partnershipController')
exports.userController = require('./userController')